### ISSUE TITLE
Does this theme is available for running over Github?

### ISSUE THREAD

**Issue by yuanjames** [rohitjain00/dev-portfolio-blog#24]
I see this theme used Js, so it is not allowed to run in Github right?

**Comment by rohitjain00** [comment]
No, having JS does not cause any issue while hosting it on Github. I'm already using this theme for my portfolio on Github.

**Comment by yuanjames** [comment]
> No, having JS does not cause any issue while hosting it on Github. I'm already using this theme for my portfolio on Github.

Hi, thanks, btw, I found a problem, when I change the '  <h1><span>I am xxx yyy </span></h1>', it does not reflect all changes, only xxx appeared, no yyy.

**Comment by rohitjain00** [comment]
Hi, just wanted to know what issues are you facing with this theme. If you could add all the issues I could act on it. @yuanjames

**Comment by yuanjames** [comment]
> Hi, just wanted to know what issues are you facing with this theme. If you could add all the issues I could act on it. @yuanjames

Thanks for your support, I am not sure the reason of the issue, I re-cloned your code (CloneAndUse) it works fine now.

**Comment by rohitjain00** [comment]
Good to know. Let me know if you have any suggestions for the next release of this theme. I was busy with the academics and work so I am not so active here. Please feel free to contribute to this.

**Comment by yuanjames** [comment]
> Good to know. Let me know if you have any suggestions for the next release of this theme. I was busy with the academics and work so I am not so active here. Please feel free to contribute to this.

Yes, very nice and my favorite theme, thanks for your work. Hope you work well.
