### ISSUE TITLE
blog list not working on jekyll 4

### ISSUE THREAD

**Issue by AsheBlade** [rohitjain00/dev-portfolio-blog#25]
After putting the posts in the _posts folder, they will not show up in the blog list. 

## issue

In blog.html, we have: 

`<ul class="blog-list">
    {% for post in paginator.posts %}`

## fix

I fixed it by changing, paginator to site. 

`<ul class="blog-list">
    {% for post in site.posts %}`

And it solved the problem.  I'm not sure if I did anything wrong, or if my jekyll version is too new (github only support jekyll 3).   But, using paginator.posts will not generate blog lists.  Basically, if people follow the instructions in the README.md, they will not be able to get a blog list. 

Hope this helps people, or other people can clarify this.

**Comment by yuanjames** [comment]
I think Github used 3.9, but 3.9 does support to generate post list in blog page.

**Comment by rohitjain00** [comment]
Thanks @AsheBlade for pointing this out. I think if we use `site.posts` instead of `paginator.posts` it will not use pagination and rather display all the blogs on a single page.

**Comment by rohitjain00** [comment]
I'm working on the jekyll version `3.8.7` and it's working fine.

**Comment by yuanjames** [comment]
> Thanks @AsheBlade for pointing this out. I think if we use `site.posts` instead of `paginator.posts` it will not use pagination and rather display all the blogs on a single page.

I followed the @AsheBlade 's suggestion, it works fine now and it is run over Github. BTW, all blogs now for me are displayed in the blog-list page.

**Comment by rohitjain00** [comment]
I'm using the `paginator.posts` and it's working fine for me. Can you check running `jekyll --version` and see the version.

**Comment by yuanjames** [comment]
> I'm using the `paginator.posts` and it's working fine for me. Can you check running `jekyll --version` and see the version.

I am not running it on my local environment, so can't check it by `jekyll -v`. I run it over Github, https://pages.github.com/versions/, it shows Github is using 3.9.0.

**Comment by rohitjain00** [comment]
@yuanjames I've tried running the website while setting up new dev env and everything's working fine. I don't see why you needed to add site.posts?

**Comment by rohitjain00** [comment]
@AsheBlade  if the blogs are working at your end can we close this issue?

**Comment by yuanjames** [comment]
> @yuanjames I've tried running the website while setting up new dev env and everything's working fine. I don't see why you needed to add site.posts?

Not sure, but anyway, thanks for your code. The blog is nice.

**Comment by AsheBlade** [comment]
Yes.  Please close.  I'm not familiar with site. Pagination.  I will read
jekyll documents and find out myself.  Again,  as always.  Thanks for your
help.
