### ISSUE TITLE
Make resume part as a web page rather than PDF link?

### ISSUE THREAD

**Issue by yuanjames** [rohitjain00/dev-portfolio-blog#27]
Hi, May I ask is it possible to make the resume part similar to the about part? rather than a PDF link.

**Comment by AsheBlade** [comment]
You can simply change the navigation.html, and make follow the style of the about.md.

**Comment by yuanjames** [comment]
Thanks

**Comment by rohitjain00** [comment]
Yes, it is possible. Although, the way I wanted this theme was to give the Resume in form of pdf. The way I see it you can just add details from resume to the About me section (Like I did :grin:)

**Comment by yuanjames** [comment]
> Yes, it is possible. Although, the way I wanted this theme was to give the Resume in form of pdf. The way I see it you can just add details from resume to the About me section (Like I did )

Thanks @rohitjain00, Yes, I used the same idea and remove the resume part from home.html. :smile:
