### ISSUE TITLE
Can I buy you a cup of coffee? 

### ISSUE THREAD

**Issue by AsheBlade** [rohitjain00/dev-portfolio-blog#28]
I really love your theme. I really do.  I will use it for two purposes: 

1. professional resume like you did. 
2. use this theme to build an online tombstone for myself after I die. 

Your theme is simple and elegant.   I just can't stop loving it. 

Can you pay you respect by supporting you? Do you have [buymeacoffee](https://www.buymeacoffee.com/) ?

**Comment by rohitjain00** [comment]
Thanks so much for your kind words, I really appreciate this. I've added a `buymeacoffee` button to the readme in the repo. 

Also, here is my page
https://www.buymeacoffee.com/rohitjain00
