### ISSUE TITLE
Bug: Homepage does not scroll. 

### ISSUE THREAD

**Issue by AsheBlade** [rohitjain00/dev-portfolio-blog#32]
## issue 

I have tested this on several phones and browsers, I'm pretty sure this is a bug. The homepage won't scroll down. 

This bug only happens on the home page. It does not happen on any other pages.   **It is an issue on phone screens. It is not too obvious on the computer screen, since the computer screens are always bigger.**

## screenshot
This is the screenshot on my phone that shows this issue. There are more sections on my navigation list, but the screen won't scroll down to show them. When the navigation list gets too long, it won't scroll down to allow users to select the section. 

![](https://lh3.googleusercontent.com/pw/ACtC-3ceFldY3O_Ee3dfQuHNX-nkL8YUfvymJoqZQEWLMTAd1xG9opd5E3npErvQyzLSLClhrIWy8j9X5IWAXA8iFVyQW0OHKKCAUqkUWLiKugEF4q1uY8Co1SAYorhqLV0Kmhmjf3dd84-mrzg7tcYyaNJU=w513-h911-no?authuser=0)

## my project

my project is [here](https://github.com/AsheBlade/Tomb). you can view my code. 

The website is hosted [here](https://asheblade.github.io/Tomb/). 

I really like your project and would really appreciate any help or suggestions from you.  I am not a front-end developer, but I suppose this could be a simple fix. 

Thanks!

**Comment by rohitjain00** [comment]
Thanks for letting me know. I've corrected the issue in this commit. Given that you've changed the theme so much you might just want to update the `scss` as did in the commit above. The problem faced was due to position fixed on the  home page.

**Comment by AsheBlade** [comment]
Again, Thank you so much.  I followed your commit and it works now. Honestly, I didn't expect a fix so soon.  I have bought sponsored you on buymecoffee. You also have my personal respect for this project.  I'm a Java backend developer focused on Springboot framework. I also have some experience with native iOS development using Xcode. If there is any project that we can work on together, it will be my pleasure.  Nice to meet you. Great work !

**Comment by rohitjain00** [comment]
Thank you so much for your kind words, Let's connect on LinkedIn.
