### ISSUE TITLE
  Conversion error in your project while converting 'assets/css/styles.scss'

### ISSUE THREAD

**Issue by AXYZdong** [rohitjain00/dev-portfolio-blog#44]
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Invalid CSS after "}": expected "}", was "" on line 272

Above is the error I met when I use the `bundle exec jekyll serve` to test in the local. However, the error just because lack  the `}` on line 272 in the 'assets/css/styles.scss' and I solve it.

Could you please modify the **styles.scss** file to help other people avoid the problem?

**Comment by rohitjain00** [comment]
Hey, thanks for reporting this issue. Will fix this in the next release.
